apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  labels:
    {{- include "ai-assist.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - aiassist.unreview.io
      secretName: ai-assist-ingress-nginx-grpc-tls
    - hosts:
        - codesuggestions.gitlab.com
      secretName: ai-assist-gitlab-ingress-nginx-grpc-tls
  rules:
    - host: aiassist.unreview.io
      http:
        paths:
          - path: /(v1|v2)/completions
            pathType: Prefix
            backend:
              service:
                name: faux-pilot
                port:
                  number: 8080
    - host: codesuggestions.gitlab.com
      http:
        paths:
          - path: /(v1|v2)/completions
            pathType: Prefix
            backend:
              service:
                name: faux-pilot
                port:
                  number: 8080
