---
description: Tracks when resolve vulnerability API is called from GitLab instance
internal_events: true
action: request_resolve_vulnerability
product_group: ai_framework
milestone: '17.3'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/1113
distributions:
  - ce
  - ee
tiers:
  - free
  - premium
  - ultimate
